### ISSUE TITLE
unable to use application correctly. error popping up when using 

### ISSUE THREAD

**Issue by saket1214** [asagrekin/GamesInOne#41]
Cannot load games into the application. Whenever i click add and I place the name of the game and the file path of the game i downloaded on my laptop, i get the following error of unable to find LinkFrontAndBack.dil:
None of the other functionality is able to be tested, like the play button, edit order, save order, and delete functionalities are not able to be tested. 
<img width="471" alt="image" src="https://github.com/asagrekin/GamesInOne/assets/130507846/c436043d-d3b3-4444-87f7-e79cd0444353">

**Comment by asagrekin** [comment]
Hey Saket,

Please remember to extract the zip of the executable before running it.
This error message should go away once you do that. If not, please let us
know.

Thanks,
Dev team

**Comment by saket1214** [comment]
yea i followed all the instructions and extracted the zip and the error keeps popping up.

**Comment by asagrekin** [comment]
In the extracted GamesOnOne directory, is there a file named
“LinkFrontAndBack.dll”?

If not, it’s possible it just got deleted or didn’t download properly. If
you try and redownload the zip it might get rid of the error.

We will look further into this tomorrow if that doesn’t solve the issue.

Please let us know either way.
Thanks again!

**Comment by saket1214** [comment]
there is a file named LinkFrontAndBack.dll and it is in the folder. but the error still keeps popping up

**Comment by asagrekin** [comment]
Does the error message pop up when you boot the app, or only when you are trying to add the game?

**Comment by saket1214** [comment]
when I boot the app and when i try to add a game. I could get around it when opening up the app, but when adding a game it is not allowing me to do so

**Comment by asagrekin** [comment]
Have you tried deleting the app and the zip, and re-downloading it?

**Comment by asagrekin** [comment]
If that doesn't work, please send a screenshot of the expanded error.

**Comment by ashleyperis** [comment]
I also had this error when I tried to add a game.

**Comment by slok1368** [comment]
@ashleyperis @saket1214 

To narrow down the cause of the issue, can you provide information for the following questions:
1. What is the your windows computer architecture?
>Windows Start > "System Information" > In the System Summary tab > the value for the item "System Type"
e.g. for me, it is x64-based PC.

2. And if possible, can you share what is being shown in the "Details" section of the popup error?

3. Apart from the beta release zip, were you also experiencing this issue when building and running the app through Visual Studio after following our developer guide?

Thank you for your patenice,
Dev Team

**Comment by asagrekin** [comment]
A recent PR merge by @slok1368  should have fixed this issue. Commit: https://github.com/asagrekin/GamesInOne/commit/9d9621a4192881e1c33317fd47f4a0d27e28180a
