### ISSUE TITLE
When opening application, error appears (still functional)

### ISSUE THREAD

**Issue by ashleyperis** [asagrekin/GamesInOne#45]
When I click on the application to run it, I get this error: 
![image](https://github.com/asagrekin/GamesInOne/assets/68792748/93898608-7a32-4804-9fd3-b1731119a6bd)
I was still able to proceed to the application with no problem when I close out of the error, but I thought that I would report that it happened. 
(I also did get the error mentioned in the other issue when I went to add a game.)

**Comment by slok1368** [comment]
Thank you for letting us know about this issue!

We are currently looking into it. For the time being, can you provide us with more information as mentioned in the other post's [comment](https://github.com/asagrekin/GamesInOne/issues/41#issuecomment-1560607440).

**Comment by asagrekin** [comment]
This is a duplicate issue, so we're closing it.
